// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VeApp: typeof import('veno-ui/components')['App']
    VeAvatar: typeof import('veno-ui/components')['Avatar']
    VeBreadcrumb: typeof import('veno-ui/components')['Breadcrumb']
    VeBreadcrumbItem: typeof import('veno-ui/components')['BreadcrumbItem']
    VeButton: typeof import('veno-ui/components')['Button']
    VeContainer: typeof import('veno-ui/components')['Container']
    VeFadeTransition: typeof import('veno-ui/components')['FadeTransition']
    VeHeader: typeof import('veno-ui/components')['Header']
    VeHeaderItems: typeof import('veno-ui/components')['HeaderItems']
    VeHeaderNavIcon: typeof import('veno-ui/components')['HeaderNavIcon']
    VeHeaderTitle: typeof import('veno-ui/components')['HeaderTitle']
    VeList: typeof import('veno-ui/components')['List']
    VeMain: typeof import('veno-ui/components')['Main']
    VeSider: typeof import('veno-ui/components')['Sider']
    VeSpacer: typeof import('veno-ui/components')['Spacer']
    VeTable: typeof import('veno-ui/components')['Table']
    VeTooltip: typeof import('veno-ui/components')['Tooltip']
  }
}

export { }
