// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VeApp: typeof import('veno-ui/components')['App']
    VeContainer: typeof import('veno-ui/components')['Container']
    VeHeader: typeof import('veno-ui/components')['Header']
    VeHeaderTitle: typeof import('veno-ui/components')['HeaderTitle']
    VeMain: typeof import('veno-ui/components')['Main']
    VeSider: typeof import('veno-ui/components')['Sider']
  }
}

export { }
