// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CoreBreadcrumb: typeof import('./components/core/CoreBreadcrumb.vue')['default']
    CoreHeader: typeof import('./components/core/CoreHeader.vue')['default']
    CoreLeftSide: typeof import('./components/core/CoreLeftSide.vue')['default']
    README: typeof import('./components/README.md')['default']
    VeApp: typeof import('veno-ui/components')['App']
    VeAvatar: typeof import('veno-ui/components')['Avatar']
    VeBreadcrumb: typeof import('veno-ui/components')['Breadcrumb']
    VeBreadcrumbItem: typeof import('veno-ui/components')['BreadcrumbItem']
    VeButton: typeof import('veno-ui/components')['Button']
    VeCard: typeof import('veno-ui/components')['Card']
    VeCode: typeof import('veno-ui/components')['Code']
    VeContainer: typeof import('veno-ui/components')['Container']
    VeDrawer: typeof import('veno-ui/components')['Drawer']
    VeFadeTransition: typeof import('veno-ui/components')['FadeTransition']
    VeH2: typeof import('veno-ui/components')['H2']
    VeHeader: typeof import('veno-ui/components')['Header']
    VeHeaderItems: typeof import('veno-ui/components')['HeaderItems']
    VeHeaderNavIcon: typeof import('veno-ui/components')['HeaderNavIcon']
    VeHeaderTitle: typeof import('veno-ui/components')['HeaderTitle']
    VeList: typeof import('veno-ui/components')['List']
    VeListItem: typeof import('veno-ui/components')['ListItem']
    VeMain: typeof import('veno-ui/components')['Main']
    VeMenu: typeof import('veno-ui/components')['Menu']
    VeP: typeof import('veno-ui/components')['P']
    VeSpacer: typeof import('veno-ui/components')['Spacer']
    VeTable: typeof import('veno-ui/components')['Table']
    VeTooltip: typeof import('veno-ui/components')['Tooltip']
  }
}

export { }
